### ISSUE TITLE
Inconsistencies between /savings and /spendings

### ISSUE THREAD

**Issue by speshak** [gruberb/YNABDoctor#54]
The `/spendings` endpoint has a nice `sumPerMonth` key which you can loop over to get the monthly sums.  `/savings` on the other hand mixes the summary values (eg `average`/`averagePercent`) at the root of the response.  Is there any reason not to update `/savings` to also have a `sumPerMonth` (or some other name) key to house the monthly data?

Right now if I want to display `/savings` data I have to loop over all object keys, and write special case code to skip over the non-date keys.

**Comment by speshak** [comment]
If resolving these differences is something that is wanted, I already cut the code here: https://github.com/speshak/YNABDoctor/tree/nest_savings_date_data

**Comment by gruberb** [comment]
Thank you @speshak 

I created a new PR for the proposed changes.
https://github.com/gruberb/YNABDoctor/pull/55
