### ISSUE TITLE
/spendings Endpoint producing duplicate data in sumPerMonth

### ISSUE THREAD

**Issue by speshak** [gruberb/YNABDoctor#56]
After the recent changes, I'm seeing duplicated data in the `/spendings` `sumPerMonth` key:

        "sumPerMonth": [
        {
            "2019-01-01": 100,
            "2019-02-01": 0
        },
        {
            "2019-01-01": 100,
            "2019-02-01": 0
        }
       ]

My currently running container was built off of d690c6c

**Comment by gruberb** [comment]
Could you maybe clean your environment and run it again (maybe via `docker-compose`?) I tried both locally and my deployed version, and I can't reproduce the duplicates!

**Comment by gruberb** [comment]
Ok, I found the problem. Thanks for the heads up! I fixed it!

I also removed the "averagePercent" since it was never accurate and needs further work.
